---
# see https://github.com/nextapps-de/flexsearch#tokenizer-prefix-search for options
tokenizer: "full" # strict, forward, reverse, full
custom_domain: ""
fail_on_validation: false
searchableAttributes:
  - "prefLabel" # you should not delete this one
  - "notation"
  - "altLabel"
#  - "hiddenLabel"
#  - "example"
  - "definition"
ui:
  title: "vocabs.arkumu.nrw" # Title is mandatory
  logo: "https://docs.arkumu.nrw/assets/images/arkumu-favicon.svg" # Path
  colors:
    skoHubWhite: "rgb(255, 255, 255)"
    skoHubDarkColor: "rgb(15, 85, 75)"
    skoHubMiddleColor: "rgb(20, 150, 140)"
    skoHubLightColor: "rgb(40, 200, 175)"
    skoHubThinColor: "rgb(55, 250, 210)"
    skoHubBlackColor: "rgb(5, 30, 30)"
    skoHubAction: "rgb(230, 0, 125)"
    skoHubNotice: "rgb(250, 180, 50)"
    skoHubDarkGrey: "rgb(155, 155, 155)"
    skoHubMiddleGrey: "rgb(200, 200, 200)"
    skoHubLightGrey: "rgb(235, 235, 235)"
  fonts:
    regular:
      font-family: 'Roboto Mono'
      font_style: "normal"
      font_weight: 400
      src: url('https://docs.arkumu.nrw/assets/fonts/RobotoMono-VariableFont_wght.woff2') format('woff2-variations');
      color: #1E1E1E;
      name: "Roboto Mono regular"
    bold:
      font_family: 'Roboto Mono'
      font_style: "normal"
      font_weight: 700
      src: url('https://docs.arkumu.nrw/assets/fonts/RobotoMono-VariableFont_wght.woff2') format('woff2-variations');
      color: #1E1E1E;
      name: "Roboto Mono bold"
  footer:
    links:
      - title: "arkumu Docs"
        url: "https://docs.arkumu.nrw"
        target: "_blank"
        rel: "noopener noreferrer"
      - title: "Impressum"
        url: "https://docs.arkumu.nrw/about"
        target: "_blank"
        rel: "noopener noreferrer"